export const ProductItems = [
  {
    name: "Baking Pan",
    categoryId: 3,
    categoryName: "kitchen",
    unitPrice: "10.99",
    status: 1,
    date: "10/26/2016",
  },
  {
    name: "Bath Rub 2",
    categoryId: 1,
    categoryName: "bath",
    unitPrice: "28.20",
    status: 1,
    date: "07/10/2016",
  },
  {
    name: "Bath Rub 3",
    categoryId: 1,
    categoryName: "bath",
    unitPrice: "27.10",
    status: 1,
    date: "07/10/2017",
  },
  {
    name: "Bath Rub 4",
    categoryId: 1,
    categoryName: "bath",
    unitPrice: "28.80",
    status: 1,
    date: "08/10/2017",
  },
  {
    name: "Bed Curtain",
    categoryId: 2,
    categoryName: "bedding",
    unitPrice: "18.60",
    status: 0,
    date: "07/11/2016",
  },
];
