import Head from "next/head";
import LoginModal from "../components/modals/loginModal";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-10 text-lg font-semibold text-center">This is the Public Landing Page | HOME PAGE</main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          {/* <span>Footer</span> */}
        </a>
      </footer>
    </div>
  );
}
