import Head from "next/head";
import { useContext } from "react";
import LoginModal from "../components/modals/loginModal";
import { authContext } from "../context/authContext";

export default function Home() {
  const { state, dispatch } = useContext(authContext);

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white p-10 text-xl text-gray-600 font-semibold text-center ">
        <div>Welcome to the Public Landing Page | HOME PAGE</div>

        {!state.user && <div>Please log in to view Product List</div>}
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          {/* <span>Footer</span> */}
        </a>
      </footer>
    </div>
  );
}
